import React from 'react';
import {ArrowRight,ChevronLeft} from 'lucide-react';

const links=[
 ['/product/cream-braided-massal-jesses','Cream Braided Massal Jesses & Leash Set'],
 ['/product/tan-braided-massal-jesses','Tan Braided Massal Jesses & Anklet Bundle'],
 ['/product/black-yellow-dowar-jesses','Black & Yellow Dowar Braided Jesses Set'],
 ['/product/black-dowar-jesses','Black Dowar Braided Jesses & Leash Bundle']
];

export default function JessesGuide(){
 return <main className="story-page guide-page"><header className="story-header"><a className="brand official" href="/"><span className="logo-crop"><img src="/brand/main-logo-small.webp" alt="Saeed Sons Falconry logo"/></span><span className="brand-words"><b>SAEED SONS</b><small>FALCONRY</small></span></a><a className="back-link" href="/shop"><ChevronLeft/> BACK TO SHOP</a></header><article className="guide-content"><span className="kicker">FIELD GUIDE / DUBAI & THE GULF</span><h1>Best jesses for falcons in Dubai.</h1><p className="guide-lead">Jesses are a small part of a falconry kit, but they carry a serious responsibility. The right pair should be supple in the hand, secure around the anklet and easy to inspect before every session.</p><h2>What falconers look for</h2><p>In Dubai, Abu Dhabi, Qatar and Saudi Arabia, falconers commonly choose braided cotton or synthetic cord for its light feel and clear handling. Traditional Gulf terms such as <i>Massal</i> and <i>Dowar</i> describe familiar braided styles and patterns rather than a substitute for correct fit. Length, cord diameter and attachment method should always be confirmed for the individual bird.</p><p>A complete setup normally pairs two jesses with properly fitted anklets, a swivel and a leash. The jesses should move freely without sharp edges, remain easy to untie when equipment is changed, and be replaced when the braid becomes worn. Never rely on colour or appearance alone: inspect the knots and attachment points before each use.</p><h2>Massal and Dowar styles</h2><p>Our cream and tan Massal sets use a softer neutral braid for a clean everyday kit. The black-and-yellow Dowar set is easier to identify in a busy mews, while the all-black Dowar bundle offers a discreet finish. Each is supplied as a product for review and sizing confirmation, so you can tell us the bird profile and the length you prefer before ordering.</p><div className="guide-products">{links.map(([href,name])=><a href={href} key={href}><span>{name}</span><ArrowRight/></a>)}</div><h2>Fit, care and responsible use</h2><p>Measure and check the equipment with an experienced falconer. Keep cord clean and dry, check for fraying after every flight, and retire any jess that has lost its shape or shows a damaged knot. Saeed Sons Falconry can help match the braid, length and anklet style to your working routine in Dubai or for international delivery.</p><a className="cta dark" href="/shop?category=jesses-swivels">SHOP JESSES & SWIVELS <ArrowRight/></a></article><footer><a className="brand official" href="/"><span className="logo-crop"><img src="/brand/main-logo-small.webp" alt="Saeed Sons Falconry logo"/></span><span className="brand-words"><b>SAEED SONS</b><small>FALCONRY</small></span></a><p>+92 324 784 8227</p></footer></main>;
}
