import React,{useEffect} from 'react';
import {ArrowRight,ChevronLeft} from 'lucide-react';

const products=[
 ['/product/cream-braided-massal-jesses','Cream Braided Massal Jesses & Leash Set','/brand/jesses/generated-cream-massal.png','Cream Massal jesses with a light braided finish.'],
 ['/product/tan-braided-massal-jesses','Tan Braided Massal Jesses & Anklet Bundle','/brand/jesses/generated-tan-massal.png','Neutral tan Massal braid for an everyday field kit.'],
 ['/product/black-yellow-dowar-jesses','Black & Yellow Dowar Braided Jesses Set','/brand/jesses/generated-black-yellow-dowar.png','High-contrast Dowar braid for easy identification.'],
 ['/product/black-dowar-jesses','Black Dowar Braided Jesses & Leash Bundle','/brand/jesses/generated-black-dowar.png','A discreet black Dowar braid and leash bundle.']
];

export default function JessesGuide(){
 useEffect(()=>{document.title='Best Jesses for Falcons in Dubai | Saeed Sons Falconry';const meta=document.querySelector('meta[name="description"]');if(meta)meta.setAttribute('content','Discover the best falcon jesses in Dubai, including Massal and Dowar braided jesses, anklets, swivels and leashes for Gulf falconry. Explore Saeed Sons Falconry products and fit guidance.');return()=>{document.title='Saeed Sons Falconry'}},[]);
 return <main className="jesses-guide"><header className="story-header"><a className="brand official" href="/"><span className="logo-crop"><img src="/brand/main-logo-small.webp" alt="Saeed Sons Falconry logo"/></span><span className="brand-words"><b>SAEED SONS</b><small>FALCONRY</small></span></a><a className="back-link" href="/shop"><ChevronLeft/> BACK TO SHOP</a></header>
  <section className="jesses-guide-hero"><img src="/brand/guides/jesses/jesses-guide-hero.png" alt="Braided Massal and Dowar falcon jesses, anklets and swivel arranged for Dubai falconry"/><div className="jesses-hero-copy"><span className="kicker">FIELD GUIDE / DUBAI & THE GULF</span><h1>Best jesses<br/><i>for falcons.</i></h1><p>Massal and Dowar braids, fit notes and field-ready choices for falconers in Dubai, Abu Dhabi, Qatar and Saudi Arabia.</p><a className="cta" href="/shop/jesses-swivels">SHOP JESSES & SWIVELS <ArrowRight/></a></div></section>
  <section className="jesses-guide-intro"><div><span className="kicker">THE CONNECTION MATTERS</span><h2>Small equipment.<br/><i>Serious responsibility.</i></h2></div><p>Jesses connect a falcon’s anklets to the swivel and leash. The best falcon jesses should feel supple, hold their shape and remain easy to inspect before every session. This guide explains what to look for when choosing braided jesses in Dubai and the wider Gulf market.</p></section>
  <section className="jesses-guide-story"><img src="/brand/guides/jesses/jesses-guide-workshop.png" alt="Falconer inspecting a braided jess, leather anklet and swivel on a workshop bench"/><div><span className="kicker">01 / FIT & MATERIAL</span><h2>Made to be checked<br/><i>before every flight.</i></h2><p>Choose cord that is consistent from knot to knot, with no fraying or sharp edges. Pair two jesses with correctly fitted anklets, then check the swivel and leash as one working system. Massal and Dowar are familiar Gulf braid styles; the right length still depends on the individual bird and anklet.</p><p>Keep jesses clean and dry, inspect the attachment points after use and replace any piece that has lost its shape. A tidy, well-fitted kit supports calm handling in the mews, on the glove and in the field.</p></div></section>
  <section className="jesses-guide-story reverse"><img src="/brand/guides/jesses/jesses-guide-field.png" alt="Hooded falcon perched safely with braided jesses visible on a falconer’s glove in the Abu Dhabi desert"/><div><span className="kicker">02 / MASSAL & DOWAR</span><h2>Traditional braids.<br/><i>Modern field clarity.</i></h2><p>Cream and tan Massal styles offer a quiet, neutral finish. Black-and-yellow Dowar makes the equipment easy to identify in a busy mews, while all-black Dowar suits a discreet working kit. We confirm bird profile, preferred length and finish before a direct order.</p><p>Browse the collection below, then message Saeed Sons Falconry for sizing help and international delivery guidance.</p><a className="cta dark" href="https://wa.me/923247848227?text=Hello%20Saeed%20Sons%20Falconry%2C%20I%20need%20help%20choosing%20jesses.">ASK ABOUT FIT <ArrowRight/></a></div></section>
  <section className="jesses-guide-products"><div className="collection-top"><div><span className="kicker">THE COLLECTION</span><h2>Choose your<br/><i>field braid.</i></h2></div><p>Four braided jesses and leash sets<br/>for Gulf falconry routines.</p></div><div className="jesses-product-grid">{products.map(([href,name,image,desc])=><a className="jesses-product-card" href={href} key={href}><div><img src={image} alt={name+' for falconry'} loading="lazy"/></div><small>JESSES & SWIVELS</small><h3>{name}</h3><p>{desc}</p><span className="text-link">VIEW PRODUCT <ArrowRight/></span></a>)}</div></section>
  <section className="jesses-guide-faq"><span className="kicker">FIELD NOTES / FAQ</span><h2>Questions falconers<br/><i>ask first.</i></h2><div><details open><summary>What are Massal and Dowar jesses?</summary><p>They are familiar braided jess styles used across Gulf falconry. The braid pattern and finish differ, while correct fit and regular inspection remain the priority.</p></details><details><summary>How do I choose a length?</summary><p>Share the bird profile, anklet style and intended use with us. We confirm a suitable length before the order is finalized.</p></details><details><summary>Can I order in bulk?</summary><p>Yes. Use WhatsApp to request a bulk quotation for matching colours, lengths and quantities.</p></details></div></section>
  <footer><a className="brand official" href="/"><span className="logo-crop"><img src="/brand/main-logo-small.webp" alt="Saeed Sons Falconry logo"/></span><span className="brand-words"><b>SAEED SONS</b><small>FALCONRY</small></span></a><p>+92 324 784 8227</p></footer></main>;
}
